class Flight {
    public String FL_DATE, MKT_CARRIER, MKT_CARRIER_FL_NUM, ORIGIN,ORIGIN_CITY_NAME,ORIGIN_STATE_ABR,ORIGIN_WAC,DEST,DEST_CITY_NAME,DEST_STATE_ABR,DEST_WAC,CRS_DEP_TIME,DEP_TIME,CRS_ARR_TIME,ARR_TIME,DISTANCE;
    public boolean CANCELLED, DIVERTED;

    Flight() {}
}
